/// <reference path="jquery-3.3.1.js" />
/// <autosync enabled="true" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
/// <reference path="umd/popper-utils.js" />
/// <reference path="umd/popper.js" />
/// <reference path="esm/popper-utils.js" />
/// <reference path="esm/popper.js" />
/// <reference path="custom/mainscript.js" />
/// <reference path="custom/rouletteengine.js" />
/// <reference path="bootstrap.bundle.js" />
/// <reference path="bootstrap.js" />
/// <reference path="_references (2).js" />
